import Head from "next/head";
import Hero from "../components/hero";
import Navbar from "../components/navbar";
import Cards from "../components/cards";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div className="relative bg-gray-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Cards />
      <Footer />
    </div>
  );
}
